ext_enabled: ["json", "synapse", "htmlparser"]
appid: BOT_ACCESS_TOKEN
homeserver: matrix-client.matrix.org
html_custom_headers: { Accept-Encoding: 'deflate, gzip, br, zstd', User-Agent: 'WhatsApp/2' }
json_max_char: 2000
max_links: 3
min_image_width: 475
max_image_embed: 300
no_results_react: ðŸ’¨
url_blacklist:
  - ':\/\/matrix\.to\/'
  - '\.pdf($|\?)'
  - '0.0.0.0'
  - '1.0.0.0/8'
  - '127.0.0.0/8'
  - '10.0.0.0/8'
  - '172.16.0.0/12'
  - '192.168.0.0/16'
  - '100.64.0.0/10'
  - '192.0.0.0/24'
  - '169.254.0.0/16'
  - '192.88.99.0/24'
  - '198.18.0.0/15'
  - '192.0.2.0/24'
  - '198.51.100.0/24'
  - '203.0.113.0/24'
  - '224.0.0.0/4'
  - '::'
  - '::1/128'
  - 'fe80::/10'
  - 'fc00::/7'
  - '2001:800::/21'
  - '2001:db8::/32'
  - '3fff:ffff:ffff:ffff:ffff:ffff:ffff:ffff'
  - 'ff00::/8'
  - 'fec0::/10'
user_blacklist:
  - '@user:example.com'
